### ISSUE TITLE
dev.0xffff.one 无法收到帐户激活邮件

### ISSUE THREAD

**Issue by bobby285271** [0xffff-one/0xffff-flarum#19]
**问题：**

dev.0xffff.one 无法收到帐户激活邮件，发帖和回帖功能无法使用（应该跟帐户没激活存在因果联系，不另外开 issue 了）。

**复现步骤：**

(1) 访问 https://dev.0xffff.one/

(2) 点击位于导航栏的 Sign Up 链接

(3) 输入合规的帐户名、密码和邮箱，点击 Sign Up

(4) 弹出提示信息如下：

```
Oops! Something went wrong. Please reload the page and try again.
```
![Screenshot_2021-04-30 0xFFFF Dev Beta 16(1)](https://user-images.githubusercontent.com/20080233/116640712-c4b3a800-a99d-11eb-951c-974e17733245.png)

(5) 点击第 4 步弹出信息的 DEBUG 链接，显示内容如下：
<details>
<summary>500 Internal Server Error</summary>

```plain
POST https://dev.0xffff.one/register

Swift_TransportException: Expected response code 220 but got an empty response in file /wwwroot/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php on line 447
Stack trace:
  1. Swift_TransportException->() /wwwroot/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:447
  2. Swift_Transport_AbstractSmtpTransport->assertResponseCode() /wwwroot/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:360
  3. Swift_Transport_AbstractSmtpTransport->readGreeting() /wwwroot/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:147
  4. Swift_Transport_AbstractSmtpTransport->start() /wwwroot/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/SendmailTransport.php:50
  5. Swift_Transport_SendmailTransport->start() /wwwroot/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php:65
  6. Swift_Mailer->send() /wwwroot/vendor/illuminate/mail/Mailer.php:521
  7. Illuminate\Mail\Mailer->sendSwiftMessage() /wwwroot/vendor/illuminate/mail/Mailer.php:288
  8. Illuminate\Mail\Mailer->send() /wwwroot/vendor/illuminate/mail/Mailer.php:212
  9. Illuminate\Mail\Mailer->raw() /wwwroot/vendor/flarum/core/src/Mail/Job/SendRawEmailJob.php:34
 10. Flarum\Mail\Job\SendRawEmailJob->handle() /wwwroot/vendor/illuminate/container/BoundMethod.php:36
 11. Illuminate\Container\BoundMethod->Illuminate\Container\{closure}() /wwwroot/vendor/illuminate/container/Util.php:40
 12. Illuminate\Container\Util->unwrapIfClosure() /wwwroot/vendor/illuminate/container/BoundMethod.php:93
 13. Illuminate\Container\BoundMethod->callBoundMethod() /wwwroot/vendor/illuminate/container/BoundMethod.php:37
 14. Illuminate\Container\BoundMethod->call() /wwwroot/vendor/illuminate/container/Container.php:611
 15. Illuminate\Container\Container->call() /wwwroot/vendor/illuminate/bus/Dispatcher.php:128
 16. Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}() /wwwroot/vendor/illuminate/pipeline/Pipeline.php:128
 17. Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() /wwwroot/vendor/illuminate/pipeline/Pipeline.php:103
 18. Illuminate\Pipeline\Pipeline->then() /wwwroot/vendor/illuminate/bus/Dispatcher.php:132
 19. Illuminate\Bus\Dispatcher->dispatchNow() /wwwroot/vendor/illuminate/queue/CallQueuedHandler.php:118
 20. Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}() /wwwroot/vendor/illuminate/pipeline/Pipeline.php:128
 21. Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() /wwwroot/vendor/illuminate/pipeline/Pipeline.php:103
 22. Illuminate\Pipeline\Pipeline->then() /wwwroot/vendor/illuminate/queue/CallQueuedHandler.php:120
 23. Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware() /wwwroot/vendor/illuminate/queue/CallQueuedHandler.php:70
 24. Illuminate\Queue\CallQueuedHandler->call() /wwwroot/vendor/illuminate/queue/Jobs/Job.php:98
 25. Illuminate\Queue\Jobs\Job->fire() /wwwroot/vendor/illuminate/queue/SyncQueue.php:43
 26. Illuminate\Queue\SyncQueue->push() /wwwroot/vendor/flarum/core/src/User/AccountActivationMailer.php:68
 27. Flarum\User\AccountActivationMailer->handle() /wwwroot/vendor/illuminate/events/Dispatcher.php:412
 28. Illuminate\Events\Dispatcher->Illuminate\Events\{closure}() /wwwroot/vendor/illuminate/events/Dispatcher.php:237
 29. Illuminate\Events\Dispatcher->dispatch() /wwwroot/vendor/flarum/core/src/Foundation/DispatchEventsTrait.php:33
 30. Flarum\User\Command\RegisterUserHandler->dispatchEventsFor() /wwwroot/vendor/flarum/core/src/User/Command/RegisterUserHandler.php:112
 31. Flarum\User\Command\RegisterUserHandler->handle() /wwwroot/vendor/illuminate/bus/Dispatcher.php:122
 32. Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}() /wwwroot/vendor/illuminate/pipeline/Pipeline.php:128
 33. Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() /wwwroot/vendor/illuminate/pipeline/Pipeline.php:103
 34. Illuminate\Pipeline\Pipeline->then() /wwwroot/vendor/illuminate/bus/Dispatcher.php:132
 35. Illuminate\Bus\Dispatcher->dispatchNow() /wwwroot/vendor/illuminate/bus/Dispatcher.php:78
 36. Illuminate\Bus\Dispatcher->dispatch() /wwwroot/vendor/flarum/core/src/Api/Controller/CreateUserController.php:45
 37. Flarum\Api\Controller\CreateUserController->data() /wwwroot/vendor/flarum/core/src/Api/Controller/AbstractSerializeController.php:102
 38. Flarum\Api\Controller\AbstractSerializeController->handle() /wwwroot/vendor/flarum/core/src/Api/Controller/AbstractCreateController.php:22
 39. Flarum\Api\Controller\AbstractCreateController->handle() /wwwroot/vendor/flarum/core/src/Api/Client.php:72
 40. Flarum\Api\Client->send() /wwwroot/vendor/flarum/core/src/Forum/Controller/RegisterController.php:59
 41. Flarum\Forum\Controller\RegisterController->handle() /wwwroot/vendor/flarum/core/src/Http/RouteHandlerFactory.php:38
 42. Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}() /wwwroot/vendor/flarum/core/src/Http/Middleware/ExecuteRoute.php:27
 43. Flarum\Http\Middleware\ExecuteRoute->process() /wwwroot/vendor/laminas/laminas-stratigility/src/Next.php:61
 44. Laminas\Stratigility\Next->handle() /wwwroot/vendor/flarum/core/src/Http/Middleware/FlarumPromotionHeader.php:29
 45. Flarum\Http\Middleware\FlarumPromotionHeader->process() /wwwroot/vendor/laminas/laminas-stratigility/src/Next.php:61
 46. Laminas\Stratigility\Next->handle() /wwwroot/vendor/flarum/core/src/Http/Middleware/ShareErrorsFromSession.php:57
 47. Flarum\Http\Middleware\ShareErrorsFromSession->process() /wwwroot/vendor/laminas/laminas-stratigility/src/Next.php:61
 48. Laminas\Stratigility\Next->handle() /wwwroot/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php:44
 49. Flarum\Http\Middleware\CheckCsrfToken->process() /wwwroot/vendor/laminas/laminas-stratigility/src/Next.php:61
 50. Laminas\Stratigility\Next->handle() /wwwroot/vendor/flarum/core/src/Http/Middleware/ResolveRoute.php:67
 51. Flarum\Http\Middleware\ResolveRoute->process() /wwwroot/vendor/laminas/laminas-stratigility/src/Next.php:61
 52. Laminas\Stratigility\Next->handle() /wwwroot/vendor/flarum/core/src/Http/Middleware/SetLocale.php:50
 53. Flarum\Http\Middleware\SetLocale->process() /wwwroot/vendor/laminas/laminas-stratigility/src/Next.php:61
 54. Laminas\Stratigility\Next->handle() /wwwroot/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php:32
 55. Flarum\Http\Middleware\AuthenticateWithSession->process() /wwwroot/vendor/laminas/laminas-stratigility/src/Next.php:61
 56. Laminas\Stratigility\Next->handle() /wwwroot/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php:52
 57. Flarum\Http\Middleware\RememberFromCookie->process() /wwwroot/vendor/laminas/laminas-stratigility/src/Next.php:61
 58. Laminas\Stratigility\Next->handle() /wwwroot/vendor/flarum/core/src/Http/Middleware/StartSession.php:61
 59. Flarum\Http\Middleware\StartSession->process() /wwwroot/vendor/laminas/laminas-stratigility/src/Next.php:61
 60. Laminas\Stratigility\Next->handle() /wwwroot/vendor/flarum/core/src/Http/Middleware/CollectGarbage.php:46
 61. Flarum\Http\Middleware\CollectGarbage->process() /wwwroot/vendor/laminas/laminas-stratigility/src/Next.php:61
 62. Laminas\Stratigility\Next->handle() /wwwroot/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php:28
 63. Flarum\Http\Middleware\ParseJsonBody->process() /wwwroot/vendor/laminas/laminas-stratigility/src/Next.php:61
 64. Laminas\Stratigility\Next->handle() /wwwroot/vendor/flarum/core/src/Http/Middleware/HandleErrors.php:57
 65. Flarum\Http\Middleware\HandleErrors->process() /wwwroot/vendor/laminas/laminas-stratigility/src/Next.php:61
 66. Laminas\Stratigility\Next->handle() /wwwroot/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php:84
 67. Laminas\Stratigility\MiddlewarePipe->process() /wwwroot/vendor/middlewares/request-handler/src/RequestHandler.php:84
 68. Middlewares\RequestHandler->process() /wwwroot/vendor/laminas/laminas-stratigility/src/Next.php:61
 69. Laminas\Stratigility\Next->handle() /wwwroot/vendor/middlewares/base-path-router/src/BasePathRouter.php:101
 70. Middlewares\BasePathRouter->process() /wwwroot/vendor/laminas/laminas-stratigility/src/Next.php:61
 71. Laminas\Stratigility\Next->handle() /wwwroot/vendor/laminas/laminas-stratigility/src/Middleware/OriginalMessages.php:42
 72. Laminas\Stratigility\Middleware\OriginalMessages->process() /wwwroot/vendor/laminas/laminas-stratigility/src/Next.php:61
 73. Laminas\Stratigility\Next->handle() /wwwroot/vendor/middlewares/base-path/src/BasePath.php:73
 74. Middlewares\BasePath->process() /wwwroot/vendor/laminas/laminas-stratigility/src/Next.php:61
 75. Laminas\Stratigility\Next->handle() /wwwroot/vendor/flarum/core/src/Http/Middleware/ProcessIp.php:24
 76. Flarum\Http\Middleware\ProcessIp->process() /wwwroot/vendor/laminas/laminas-stratigility/src/Next.php:61
 77. Laminas\Stratigility\Next->handle() /wwwroot/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php:84
 78. Laminas\Stratigility\MiddlewarePipe->process() /wwwroot/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php:73
 79. Laminas\Stratigility\MiddlewarePipe->handle() /wwwroot/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php:96
 80. Laminas\HttpHandlerRunner\RequestHandlerRunner->run() /wwwroot/vendor/flarum/core/src/Http/Server.php:44
 81. Flarum\Http\Server->listen() /wwwroot/public/index.php:26
```

</details>

(6) 关闭小窗，点击导航栏的 Log In 链接

(7) 输入第 3 步填写的帐户和密码，成功登录

(8) 页面顶部出现横幅如下（对邮箱地址进行了处理）：

![Screenshot_2021-04-30 0xFFFF Dev Beta 16(3)](https://user-images.githubusercontent.com/20080233/116641195-ce89db00-a99e-11eb-99da-a35c8a2d9c7b.png)

(9) 检查第 3 步填写的邮箱，没有收到任何与帐户激活相关的邮件

(10) 点击 RESEND CONFIRMATION EMAIL，页面左下角出现以下提示：

![Screenshot_2021-04-30 0xFFFF Dev Beta 16(4)](https://user-images.githubusercontent.com/20080233/116641565-87501a00-a99f-11eb-82b2-4c790f440a83.png)

(11) 点击第 10 步弹出信息的 DEBUG 链接，显示内容如下：

<details>
<summary>500 Internal Server Error</summary>

```
POST https://dev.0xffff.one/api/users/5/send-confirmation

Swift_TransportException: Expected response code 220 but got an empty response in /wwwroot/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:447
Stack trace:
#0 /wwwroot/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(360): Swift_Transport_AbstractSmtpTransport->assertResponseCode('', Array)
#1 /wwwroot/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(147): Swift_Transport_AbstractSmtpTransport->readGreeting()
#2 /wwwroot/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/SendmailTransport.php(50): Swift_Transport_AbstractSmtpTransport->start()
#3 /wwwroot/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(65): Swift_Transport_SendmailTransport->start()
#4 /wwwroot/vendor/illuminate/mail/Mailer.php(521): Swift_Mailer->send(Object(Swift_Message), Array)
#5 /wwwroot/vendor/illuminate/mail/Mailer.php(288): Illuminate\Mail\Mailer->sendSwiftMessage(Object(Swift_Message))
#6 /wwwroot/vendor/illuminate/mail/Mailer.php(212): Illuminate\Mail\Mailer->send(NULL, Array, Object(Closure))
#7 /wwwroot/vendor/flarum/core/src/Mail/Job/SendRawEmailJob.php(34): Illuminate\Mail\Mailer->raw('Hey bobby285274...', Object(Closure))
#8 /wwwroot/vendor/illuminate/container/BoundMethod.php(36): Flarum\Mail\Job\SendRawEmailJob->handle(Object(Illuminate\Mail\Mailer))
#9 /wwwroot/vendor/illuminate/container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#10 /wwwroot/vendor/illuminate/container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#11 /wwwroot/vendor/illuminate/container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Container\Container), Array, Object(Closure))
#12 /wwwroot/vendor/illuminate/container/Container.php(611): Illuminate\Container\BoundMethod::call(Object(Illuminate\Container\Container), Array, Array, NULL)
#13 /wwwroot/vendor/illuminate/bus/Dispatcher.php(128): Illuminate\Container\Container->call(Array)
#14 /wwwroot/vendor/illuminate/pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Flarum\Mail\Job\SendRawEmailJob))
#15 /wwwroot/vendor/illuminate/pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Flarum\Mail\Job\SendRawEmailJob))
#16 /wwwroot/vendor/illuminate/bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#17 /wwwroot/vendor/illuminate/queue/CallQueuedHandler.php(118): Illuminate\Bus\Dispatcher->dispatchNow(Object(Flarum\Mail\Job\SendRawEmailJob), false)
#18 /wwwroot/vendor/illuminate/pipeline/Pipeline.php(128): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}(Object(Flarum\Mail\Job\SendRawEmailJob))
#19 /wwwroot/vendor/illuminate/pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Flarum\Mail\Job\SendRawEmailJob))
#20 /wwwroot/vendor/illuminate/queue/CallQueuedHandler.php(120): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#21 /wwwroot/vendor/illuminate/queue/CallQueuedHandler.php(70): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\Queue\Jobs\SyncJob), Object(Flarum\Mail\Job\SendRawEmailJob))
#22 /wwwroot/vendor/illuminate/queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\SyncJob), Array)
#23 /wwwroot/vendor/illuminate/queue/SyncQueue.php(43): Illuminate\Queue\Jobs\Job->fire()
#24 /wwwroot/vendor/flarum/core/src/Api/Controller/SendConfirmationEmailController.php(87): Illuminate\Queue\SyncQueue->push(Object(Flarum\Mail\Job\SendRawEmailJob))
#25 /wwwroot/vendor/flarum/core/src/Http/RouteHandlerFactory.php(38): Flarum\Api\Controller\SendConfirmationEmailController->handle(Object(Laminas\Diactoros\ServerRequest))
#26 /wwwroot/vendor/flarum/core/src/Http/Middleware/ExecuteRoute.php(27): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}(Object(Laminas\Diactoros\ServerRequest), Array)
#27 /wwwroot/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\ExecuteRoute->process(Object(Laminas\Diactoros\ServerRequest), Object(Closure))
#28 /wwwroot/vendor/flarum/core/src/Api/Middleware/ThrottleApi.php(33): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#29 /wwwroot/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Api\Middleware\ThrottleApi->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#30 /wwwroot/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php(44): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#31 /wwwroot/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\CheckCsrfToken->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#32 /wwwroot/vendor/flarum/core/src/Http/Middleware/ResolveRoute.php(67): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#33 /wwwroot/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\ResolveRoute->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#34 /wwwroot/vendor/flarum/core/src/Http/Middleware/SetLocale.php(50): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#35 /wwwroot/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\SetLocale->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#36 /wwwroot/vendor/flarum/core/src/Http/Middleware/AuthenticateWithHeader.php(55): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#37 /wwwroot/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\AuthenticateWithHeader->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#38 /wwwroot/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(32): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#39 /wwwroot/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\AuthenticateWithSession->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#40 /wwwroot/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(52): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#41 /wwwroot/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\RememberFromCookie->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#42 /wwwroot/vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#43 /wwwroot/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\StartSession->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#44 /wwwroot/vendor/flarum/core/src/Api/Middleware/FakeHttpMethods.php(29): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#45 /wwwroot/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Api\Middleware\FakeHttpMethods->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#46 /wwwroot/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#47 /wwwroot/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\ParseJsonBody->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#48 /wwwroot/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#49 /wwwroot/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\HandleErrors->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#50 /wwwroot/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#51 /wwwroot/vendor/middlewares/request-handler/src/RequestHandler.php(84): Laminas\Stratigility\MiddlewarePipe->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#52 /wwwroot/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\RequestHandler->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#53 /wwwroot/vendor/middlewares/base-path-router/src/BasePathRouter.php(101): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#54 /wwwroot/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\BasePathRouter->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#55 /wwwroot/vendor/laminas/laminas-stratigility/src/Middleware/OriginalMessages.php(42): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#56 /wwwroot/vendor/laminas/laminas-stratigility/src/Next.php(61): Laminas\Stratigility\Middleware\OriginalMessages->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#57 /wwwroot/vendor/middlewares/base-path/src/BasePath.php(73): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#58 /wwwroot/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\BasePath->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#59 /wwwroot/vendor/flarum/core/src/Http/Middleware/ProcessIp.php(24): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#60 /wwwroot/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\ProcessIp->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#61 /wwwroot/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#62 /wwwroot/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(73): Laminas\Stratigility\MiddlewarePipe->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\EmptyPipelineHandler))
#63 /wwwroot/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(96): Laminas\Stratigility\MiddlewarePipe->handle(Object(Laminas\Diactoros\ServerRequest))
#64 /wwwroot/vendor/flarum/core/src/Http/Server.php(44): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#65 /wwwroot/public/index.php(26): Flarum\Http\Server->listen()
#66 {main}
```

</details>

(12) 再次检查第 3 步填写的邮箱，依然没有收到任何与帐户激活相关的邮件

**期望的结果：**

注册表单提交后收到帐户激活邮件且使用该邮件成功激活帐户，帐户激活后回贴、发帖功能正常使用。

**浏览器：**

Firefox 87.0

**补充说明：**

无法发帖演示如下：

![Screenshot_2021-04-30 0xFFFF Dev Beta 16(5)](https://user-images.githubusercontent.com/20080233/116642568-c8492e00-a9a1-11eb-9820-99a5e77a2b60.png)

无法回帖演示如下（操作所在页面为 dev.0xffff.one/d/1）：

![Screenshot_2021-04-30 第一条测试帖子 - 0xFFFF Dev Beta 16](https://user-images.githubusercontent.com/20080233/116642641-ef076480-a9a1-11eb-9b70-6152563d3c0a.png)

在测试站注册多个账号（`bobby285271` `bobby285272` `bobby285273` `bobby285274`）填写 QQ、126、使用个人域名的阿里企业邮箱进行测试，均可复现上述情况（前三个帐号为三天前注册，至今未收到邮件）。在主站下通过『更换邮箱』测试发信功能，可以顺利收到 0xffff AT izgq DOT net 发来的邮件并顺利完成邮箱验证。

其它功能暂未发现问题（包括更换头像、更改站点语言和 Follow 帖子）。

**Comment by zgq354** [comment]
sorry! 忘记配置邮件发送了，晚点我加上

**Comment by zgq354** [comment]
恢复了
![image](https://user-images.githubusercontent.com/9024954/117000360-89a1d380-ad13-11eb-9bc3-bbffd9152cc9.png)
